// <auto-generated />
namespace Protiviti.Boilerplate.Server.Migrations.RegistrationContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UpdateDateTimeColumnsOnRegistrationTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateDateTimeColumnsOnRegistrationTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201410161754500_UpdateDateTimeColumnsOnRegistrationTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
