// <auto-generated />
namespace Protiviti.Boilerplate.Server.Migrations.ApplicationWizardContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewProgramsProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewProgramsProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201409251609165_NewProgramsProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
